### ISSUE TITLE
在自己的数据及上训练结果不理想

### ISSUE THREAD

**Issue by zhuwanling** [hyperplane-lab/ACL-GAN#13]
![1617538209(1)](https://user-images.githubusercontent.com/25894416/113508306-d8781400-9581-11eb-8a44-7f6a014db185.png)
训练后test_batch生成图像颜色有问题，请问可能是什么原因啦?

**Comment by Rivendile** [comment]
你好，可能的原因有：
1. 不同的超参数可能导致不一样的结果，换用数据集之后可能需要调整；
2. 模型中用到了Batch Normalization，需要开启test模式测试；
3. 可以尝试一起test多个不同的图片
