### ISSUE TITLE
aclmaskpermg_Trainer is not defined

### ISSUE THREAD

**Issue by xunings** [hyperplane-lab/ACL-GAN#2]
Hi,
I am trying to reproduce the selfie2anime results of ACL-GAN, but I am getting the following error while training,
``NameError: name 'aclmaskpermg_Trainer' is not defined``

It seems that various trainers are supposed to be implemented in trainer.py, e.g., aclmaskpermg_Trainer, aclmaskpermg_Trainer, etc. But only one (aclgan_Trainer) is actually available. 

https://github.com/hyperplane-lab/ACL-GAN/blob/fd11bded45a0c0be2c0ddd9c6030a2f9ead884be/trainer.py#L14

Would you help with this issue? Thanks.

**Comment by Rivendile** [comment]
I'm sorry for making this mistake when I update this repo. I have fixed the code for train and test. Please let me know if there are further errors.

**Comment by xunings** [comment]
Another error (parent class not found) is raised from the following line
https://github.com/hyperplane-lab/ACL-GAN/blob/69c112cf1d8970896e9608fc616c2f05f9bacf96/trainer.py#L16

``NameError: name 'aclmaskpermgidtno_Trainer' is not defined``


There are similar issues in the test scripts,

https://github.com/hyperplane-lab/ACL-GAN/blob/69c112cf1d8970896e9608fc616c2f05f9bacf96/test_batch.py#L9

https://github.com/hyperplane-lab/ACL-GAN/blob/69c112cf1d8970896e9608fc616c2f05f9bacf96/test.py#L9

**Comment by Rivendile** [comment]
The error has been fixed.

**Comment by xunings** [comment]
> The error has been fixed.

Thanks for the update! The code is runnable now for male2female.
Will you also release a config file for selfie2anime? I am raising another issue for this.
