### ISSUE TITLE
Config for selfie2anime

### ISSUE THREAD

**Issue by xunings** [hyperplane-lab/ACL-GAN#3]
Hi,
Will you release a config file for selfie2anime? I made a selfie2anime.yaml based on male2female.yaml and the description in your paper (section 3.4), but I am not sure if it is correct.

https://github.com/xunings/ACL-GAN/blob/try_20200916/configs/selfie2anime.yaml

```bash
--- male2female.yaml	2020-09-14 15:37:06.527980140 +0800
+++ selfie2anime.yaml	2020-09-16 16:57:36.322611679 +0800
@@ -20,11 +20,11 @@
 step_size: 100000             # how often to decay learning rate
 gamma: 0.5                    # how much to decay learning rate
 gan_w: 1                      # weight of adversarial loss
-gan_cw: 0.2                   # weight of council loss
-focus_loss: 0.025             # weight of focus loss
+gan_cw: 0.5                   # weight of council loss
+focus_loss: 0.000             # weight of focus loss
 focus_delta: 0.001            # hyper parameter for focus loss
-focus_upper: 0.5              # hyper parameter for focus loss
-focus_lower: 0.3              # hyper parameter for focus loss
+focus_upper: 0.0              # hyper parameter for focus loss
+focus_lower: 0.0              # hyper parameter for focus loss
 focus_epsilon: 0.01           # hyper parameter for focus loss
 recon_x_w: 1                  # weight of image reconstruction loss
 recon_s_w: 1                  # weight of style reconstruction loss
@@ -40,7 +40,7 @@
   dim: 64                     # number of filters in the bottommost layer
   mlp_dim: 256                # number of filters in MLP
   style_dim: 8                # length of style code
-  output_dim: 4               # length of style code
+  output_dim: 3               # length of style code
   activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
   n_downsample: 2             # number of downsampling layers in content encoder
   n_res: 4                    # number of residual blocks in content encoder/decoder
@@ -61,5 +61,6 @@
 new_size: 256                               # first resize the shortest image side to this size
 crop_image_height: 256                      # random crop image of this height
 crop_image_width: 256                       # random crop image of this width
-data_root: /raid/zhaoyihao/pytorch-CycleGAN-and-pix2pix/datasets/male2female      # dataset folder location
-data_kind: male2female
\ No newline at end of file
+# data_root: /storage04/users/shaoxuning/projects/acgface/try/ACL-GAN/datasets/selfie2anime      # dataset folder location
+data_root: ./datasets/selfie2anime
+data_kind: selfie2anime
\ No newline at end of file

```

**Comment by Rivendile** [comment]
The config file is correct for selfie2anime.

**Comment by Rivendile** [comment]
The config file is correct except for max_iter which should be 350000.

**Comment by xunings** [comment]
> The config file is correct except for max_iter which should be 350000.

I just trained selfie2anime using the above mentioned selfie2anime.yaml, picked gen_00350000.pt, and tried to reproduce Fig. 7 of the paper.

Using ``test_batch.py``, I got
https://drive.google.com/file/d/1CFitMYpXfX5IihoFOP0l0asKvw3smWXn/view?usp=sharing
which is obviously worse than that in the paper.

My test command is 
``bash
python3 test_batch.py --config configs/selfie2anime.yaml --input_folder datasets/selfie2anime/testA_ACL --output_folder outputs/images/batch_s2a_acl_00350000_20200921 --checkpoint outputs/selfie2anime/checkpoints/gen_00350000.pt
``

Using ``test.py`` for one image (female_17878.jpg), I got
https://drive.google.com/file/d/1JX0wTT4at4EipiYyLbdW2rwyCMxgbSLz/view?usp=sharing


Is there anything wrong with my training / testing process?

**Comment by Rivendile** [comment]
It's obviously not consistent with our training results and we will figure it out.

**Comment by xunings** [comment]
> It's obviously not consistent with our training results and we will figure it out.

Thanks. Pls keep me updated here.
