### ISSUE TITLE
how to dataset configuration?

### ISSUE THREAD

**Issue by kimtaehyeong** [hyperplane-lab/ACL-GAN#4]
Hello.
I am very interested in your research field. So, I want to apply it to our domain.
Currently, I modified the configs file and put the dataset, but I got the following error.

"""
path = self.imgs[index]
IndexError: list index out of range
"""

I’m going to change the current dataset configuration

./datasets/selfie2anime/
In the folder above
"""
trainA
trainB
testA
testB
"""

Contains data in four configurations.
How to configure the dataset?
Thank you.

**Comment by Rivendile** [comment]
@kimtaehyeong Thanks for your interest. The dataset should be save as the following format:
/dataset
|   /train
|   |   /trainA
|   |   /trainB
|   /test
|   |   /testA
|   |   /testB

**Comment by kimtaehyeong** [comment]
Thank you so much!

**Comment by zhanghaobucunzai** [comment]
能提供下数据集下载地址不

**Comment by kimtaehyeong** [comment]
https://www.kaggle.com/arnaud58/selfie2anime
or
https://github.com/t04glovern/selfie2anime-tutorial/blob/master/.blog/README.md#Dataset-Collection-&-Preparation
