### ISSUE TITLE
GrayScale Image training

### ISSUE THREAD

**Issue by chokyungjin** [hyperplane-lab/ACL-GAN#5]
I'm so happy to meet your code. Thanks again.
But I have a question!
I want to train model using grayscale image. 
I modified input_dim_a , input_dim_b 3 to 1, and output_dim 4 to 2.
But there's still an error in the code , So I change split(3,1) to split(1,1)
https://github.com/hyperplane-lab/ACL-GAN/blob/43936793d41e07af41a7e9ed69c41a773f4577b5/trainer.py#L108
and 
I change torch.cat((x_a, x_A_fake), -3) to torch.cat((x_a, x_A_fake), -2) 
https://github.com/hyperplane-lab/ACL-GAN/blob/43936793d41e07af41a7e9ed69c41a773f4577b5/trainer.py#L279

I wanted the input channel 1 and the output to come out channel 1.
Is this the right way?

Thanks again!

**Comment by Rivendile** [comment]
I think torch.cat((x_a, x_A_fake), -2) should be remained as torch.cat((x_a, x_A_fake), -3), because the -2/-3 represent the dimension for concatenation. You can also try to print the tensor shape during and after forward propagation. Please let me know if there are further errors.

**Comment by chokyungjin** [comment]
Thanks Quick Reply!
I change -2 to -3, But I got this error.

user@5d4e343dfc5c:/workspace/data/ImageToImage/ACL-GAN$ CUDA_VISIBLE_DEVICES=2 python train.py --config configs/male2female.yaml
/workspace/data/ImageToImage/ACL-GAN/utils.py:129: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(stream)
Elapsed time in update: 1.047803
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    trainer.dis_update(images_a, images_b, config)
  File "/workspace/data/ImageToImage/ACL-GAN/trainer.py", line 289, in dis_update
    self.loss_dis_2 = self.dis_2.calc_dis_loss(x_A_A1_pair, x_A_A2_pair)
  File "/workspace/data/ImageToImage/ACL-GAN/networks.py", line 63, in calc_dis_loss
    outs0 = self.forward(input_fake)
  File "/workspace/data/ImageToImage/ACL-GAN/networks.py", line 53, in forward
    outputs.append(model(x))
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/data/ImageToImage/ACL-GAN/networks.py", line 368, in forward
    x = self.conv(self.pad(x))
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 1, 4, 4], expected input[1, 2, 514, 514] to have 1 channels, but got 2 channels instead

Also, I modified not only previous my issue, but also all split(3,1) to split(1,1) about split() code.

**Comment by Rivendile** [comment]
@chokyungjin Hi, what's the shape of your input and output? Are they [1,1,514,514]? Maybe you should change the input_dim_b from 6 to 2, which represents the input dimension of D_2.

**Comment by chokyungjin** [comment]
@Rivendile  No! My Input data size is 1024,1024.
I changed the image size to 512 by modifying the transform code. I want the output to be 512 size.
And I'll show you male2female.yaml file! Which parameter should I modify?

Thanks!

![image](https://user-images.githubusercontent.com/46750574/99029008-af47ee80-25b4-11eb-99a3-0f6d706c62dc.png)

**Comment by Rivendile** [comment]
The input_dim_b in data options should be 2 rather than 1.

**Comment by chokyungjin** [comment]
Thanks. But the model still doesn't work. There's been an error here since the all using split(3,1) code was rechanged.
![image](https://user-images.githubusercontent.com/46750574/99029784-bd970a00-25b6-11eb-98cc-c98a40d2ceef.png)

**Comment by Rivendile** [comment]
It would be much clearer if you could print the shape of these tensors.

**Comment by chokyungjin** [comment]
@Rivendile Oh, I'm sorry. I printed the shape of tensors in focus_translation func. 
my input image shape is (512,512),
print(x_fg.shape) = torch.Size([1, 3, 552, 552])
print(x_bg.shape) = torch.Size([1, 1, 555, 555])
print(x_focus.shape) = torch.Size([1, 1, 552, 552])
print(x_map.shape) = torch.Size([1, 3, 552, 552])

**Comment by Rivendile** [comment]
It is strange that the dimension 1 of x_fg and x_map is 3. 
Maybe you should change this line 
https://github.com/hyperplane-lab/ACL-GAN/blob/43936793d41e07af41a7e9ed69c41a773f4577b5/trainer.py#L87
to `x_map = x_map.repeat(1, 1, 1, 1)`

**Comment by chokyungjin** [comment]
@Rivendile I've also tried it. But it is not solved.

![image](https://user-images.githubusercontent.com/46750574/99034868-7cf0be00-25c1-11eb-8122-9850a002ca67.png)

**Comment by Rivendile** [comment]
It seems that the image sizes are not consistent. The network is designed for image size 256x256. If you want to translate images with size 512x512, maybe you should change the network accordingly, since the tensor shape of x_fg, x_bg, x_focus, and x_map are not 512.

Besides, the shape of x_bg should be identical to the input image, which is not in the shape you printed. There may be some mistakes in your preprocessing. Looking into preprocessing may also help.

**Comment by chokyungjin** [comment]
Ok, Thanks. I'm so appreciate!

**Comment by Rivendile** [comment]
I will close this issue. Feel free to reopen it if there are further errors:)
