### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by shoukna** [hyperplane-lab/ACL-GAN#6]
Hi, thanks for your brilliant work.

Can you share the evaluation code of KID and FID used in the paper? And I have a question, in the paper you compare the light mode of U-GAT-IT, have you compared the results with the U-GAT-IT's full mode?

**Comment by Rivendile** [comment]
Thanks for your interest.
We use the evaluation code here: https://github.com/taki0112/GAN_Metrics-Tensorflow.
We haven't compared the results with the U-GAT-IT's full mode for its extreme large number of parameters, which is almost 12x of ours.

**Comment by shoukna** [comment]
Thank you!
