### ISSUE TITLE
no relu/sigmoid activation on style MLP?

### ISSUE THREAD

**Issue by bilal2vec** [hyperplane-lab/ACL-GAN#9]
Hi!

I was working on replicating your paper in Jax (https://github.com/bkkaggle/jax-gans/blob/main/aclgan-selfie.py) when I ran into a question about your AdaIN and MLP implementation.

It looks like your MLP: https://github.com/hyperplane-lab/ACL-GAN/blob/4a30f933dfe9ee98650a4cc8c19fb607faec57aa/networks.py#L280 doesn't use any output activation to limit the output to only positive numbers which means that the generated means and variances that are used for scaling the activations in AdaIN can be negative, which then means that when F.batch_norm uses that variance to calculate the stddev `sqrt(var + eps)` for AdaIN, any negative values of var would become NaNs.

I'm not 100% that my reasoning is correct or if this ends up causing a problem when training though, so is this something that is supposed to happen?

**Comment by Rivendile** [comment]
Thanks for your interest. We use the same network.py as MUNIT and we did not encounter errors in training. But your guess is theoretically reasonable.
